//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        public string Código_de_carrera { get; set; }
        public string Nombre_de_carrera { get; set; }
        public Nullable<int> Cantidad_de_clases { get; set; }
        public Nullable<int> Cantidad_de_Maestros { get; set; }
    }
}
