//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        public string Código_de_clase { get; set; }
        public string Descripción_de_clase { get; set; }
        public string Tipo { get; set; }
    }
}
