//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoEntities : DbContext
    {
        public ProyectoEntities()
            : base("name=ProyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Carrera> Carreras { get; set; }
        public virtual DbSet<Clase> Clases { get; set; }
        public virtual DbSet<Clases_Carrera> Clases_Carreras { get; set; }
        public virtual DbSet<Clases_Maestro> Clases_Maestros { get; set; }
        public virtual DbSet<Solicitude> Solicitudes { get; set; }
    }
}
