//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitude
    {
        public string Código_de_solicitud { get; set; }
        public string Código_usuario { get; set; }
        public string Fecha { get; set; }
        public string Cantidad_a_color { get; set; }
        public string Cantidad_blanco_y_negro { get; set; }
        public string Tipo { get; set; }
        public string Código_de_clase { get; set; }
        public string Código_de_maestro { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
    }
}
