//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Código { get; set; }
        public string Contraseña { get; set; }
        public string Identidad { get; set; }
        public string Nombre_Completo { get; set; }
        public string Género { get; set; }
        public string Correo { get; set; }
        public string Teléfono { get; set; }
        public string Rol { get; set; }
    }
}
